name: Update Fear and Greed Index

on:
  schedule:
    - cron: '0 0 * * *' # This runs the job daily at midnight UTC
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  update-fng:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Fear and Greed Index CSV
        run: curl -o fng_data.csv https://api.alternative.me/fng/?format=csv

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add fng_data.csv
          git commit -m "Update Fear and Greed Index data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
